name: WEVREG
channels:
  - anaconda
  - pytorch
  - defaults
dependencies:
  - faiss-cpu=1.5.1
  - matplotlib=3.0.3
  - numpy=1.16.2
  - numpy-base=1.16.2
  - pandas=0.24.2
  - pip=19.0.3
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytorch=1.0.1
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - setuptools=41.0.0
  - six=1.12.0
  - tk=8.6.8
  - torchvision=0.2.2
  - wheel=0.33.1
  - joblib=0.13.2
  - statsmodels=0.11.1

